export const FETCH_VIDEO = 'FETCH_VIDEO';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_FAILED = 'FETCH_VIDEO_FAILED';

export const CREATE_VIDEO = 'CREATE_VIDEO';
export const CREATE_VIDEO_SUCCESS = 'CREATE_VIDEO_SUCCESS';
export const CREATE_VIDEO_FAILED = 'CREATE_VIDEO_FAILED';

export const OPEN_VIDEO_SHARING = 'OPEN_VIDEO_SHARING';
export const CLOSE_VIDEO_SHARING = 'CLOSE_VIDEO_SHARING';
