version: "3.8"
services:
  proxy:
    container_name: proxy
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      default:
        aliases:
          - proxy

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: "no"
    volumes:
      - ./backend:/app
    networks:
      default:
        aliases:
          - api
networks:
  default:
    name: myapp_default
